version: "3"
services:
    app:
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - ./:/social_media_API
      command: >
        sh -c "
              python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py loaddatautf8 --traceback fixture_db_tables_data.json &&
              python manage.py runserver 0.0.0.0:8000"
      env_file:
        - .env
      depends_on:
        - db

    db:
      image: postgres:14-alpine
      env_file:
        - .env
      volumes:
        - db_data:/var/lib/postgresql/data

    axigen_mail_service:
      image: axigen/axigen
      container_name: axigen
      restart: always
      volumes:
        - axigen_data:/axigen/var
      ports:
        # Non-secure ports
        - "25:25"    # SMTP
        - "110:110"  # POP3
        - "143:143"  # IMAP

        # Secure ports
        - "465:465"    # SMTP (TLS)
        - "993:993"    # IMAP (TLS)
        - "995:995"    # POP3 (TLS)
      depends_on:
        - app

volumes:
  db_data:
    driver: local
  axigen_data:
